- Content.Client/_Goobstation/Emoting/AnimatedEmotesSystem.cs
- Content.Shared/_Goobstation/Emoting/AnimatedEmotesComponent.cs
- Resources/Prototypes/DeltaV/Entities/Mobs/Species/harpy.yml
- Resources/Prototypes/DeltaV/Voice/speech_emote_sounds.yml
- Resources/Prototypes/DeltaV/Voice/speech_emotes.yml
- Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
- Resources/Prototypes/Nyanotrasen/Voice/speech_emotes.yml
- Resources/Prototypes/Voice/speech_emotes.yml
- Resources/Prototypes/_ShibaStation/SoundCollections/harpy_emote_soundcollection.yml
- Resources/Prototypes/_ShibaStation/Voice/harpy_emote_sounds.yml
- Resources/Prototypes/_ShibaStation/Voice/harpy_speech_emotes.yml
Expanded harpy emotes to be more specific when imitating other genders and species, as well as a few minor additions and tweaks. Also separated out all the harpy specific emote triggers (where possible) since it's a huge list.
harpy funny soundboard birbs 
Moved all harpy specific triggers/soundcollections out of the DeltaV shared emotes/collections yml to their own exclusive one just for readability and split up and separated some sound effects into new triggers to be more specific
> Harpy emote rework

- Resources/Changelog/ShibaChangelog.yml
- Resources/Prototypes/Loadouts/loadout_groups.yml
- Resources/Prototypes/Voice/speech_emotes.yml
Missing NT towel and lizzer emotes appear in everyone's emote wheel. not even gonna bother with a fancy pr thing blehblehbleh
> Assorted fixes

- Resources/Prototypes/InventoryTemplates/aghost_inventory_template.yml
i also made a pr on upstream but i want this now and dunno if they'll accept it :)
> Give aghosts FOUR pockets 'cause it's just handy

- Content.Server/Cargo/Components/StationCargoOrderDatabaseComponent.cs
- Content.Server/Cargo/Systems/CargoSystem.Orders.cs
- Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
- Content.Server/Entry/EntryPoint.cs
- Content.Server/Kitchen/Components/SharpComponent.cs
- Content.Server/_Goobstation/Ghostbar/GhostBarSystem.cs
- Content.Server/_Goobstation/Heretic/EntitySystems/HereticRitualSystem.cs
- Content.Server/_Goobstation/ServerCurrency/ServerCurrencyManager.cs
- Content.Server/_Shitmed/Medical/Surgery/GhettoSurgerySystem.cs
- Content.Shared/Cargo/CargoOrderData.cs
- Content.Shared/Cargo/Prototypes/CargoProductPrototype.cs
- Content.Shared/_Shitmed/Surgery/Tools/BoneSawComponent.cs
- Content.Shared/_Shitmed/Surgery/Tools/ScalpelComponent.cs
- Resources/Changelog/GoobChangelog.yml
- Resources/Locale/en-US/cargo/cargo-console-component.ftl
- Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
Pulling in some fixes to hopefully fix a few issues.
> Emergency Merge

- Resources/Prototypes/Entities/Mobs/Species/base.yml
This is PR'd to Goob Upstream but I'm impatient so I'm doing it here now.
> Fix being unable to escape being carried

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
I love our spiders, they're the best spiders, they really are. You won't get spiders like this anywhere else. I know spiders, I know a good spider. I've worked with spiders all my life.
> Make Spiders Hostile Again

- Resources/Prototypes/GameRules/events.yml
Made more adjustments to events, min pop requirements to trigger, and a few adjustments to delays between some of the more annoying ones that felt way more frequent than they should be.
> Event Tweaks (AGAIN)

- Resources/Changelog/Parts/pun-pun-fight.yml
- Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
Pun Pun will now actively defend himself and the bar from hostile threats, and also do a little bit of pest control too.
* Spiders, slimes, snakes and the Blob are now active targets for Pun Pun
* Mice, snails and roaches are also targets of his ire.
Pun Pun is CREW and should be treated as such!
> Pun Pun has been trained in self defense

- Content.Server/_DeltaV/CartridgeLoader/Cartridges/NanoChatCartridgeSystem.cs
- Content.Server/_DeltaV/NanoChat/NanoChatSystem.cs
- Content.Shared/_DeltaV/NanoChat/NanoChatCardComponent.cs
Ports https://github.com/Goob-Station/Goob-Station/pull/1313 early
> Nanochat notif fixes

- Resources/Prototypes/Catalog/Cargo/cargo_medical.yml
Ports https://github.com/Goob-Station/Goob-Station/pull/1323 early.
> Add Surgical Supplies to Cargo Catalog.

- Resources/Prototypes/_Goobstation/Entities/Objects/Materials/materials.yml
Also PR'd to goob at https://github.com/Goob-Station/Goob-Station/pull/1332 but applying early here :)
> BS Crystals are ore baggable again

- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
Early https://github.com/Goob-Station/Goob-Station/pull/1335 merge.
> Fix BSO Icon

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Adds cockroaches to the mouse faction
Ensures that cockroaches are treated the same as mice, mothroaches, snails and lootbugs - which is to say, with extreme prejudice from PetsNT like Shiva, Aves and Pun Pun.
added the npc faction to cockroaches???
computer, generate a picture of a cockroach getting bodied
> Adds cockroaches to the mouse faction (pests)

- Content.Server/_ShibaStation/Speech/Components/IllismAccentComponent.cs
- Content.Server/_ShibaStation/Speech/EntitySystems/IllismAccentSystem.cs
- Resources/Locale/en-US/_ShibaStation/traits/traits.ftl
- Resources/Prototypes/_ShibaStation/Traits/speech.yml
Added the Illism Accent as a trait, which forces your character to speak in the third person.
It's a quirk I've wanted for a while, and I've finally managed to implement it the way I wanted to.
* First utterances of any personal pronoun (I, Me) is replaced with your characters first name, or in the case of Makes-The-Funny lizard names, it'll pick the first word before the hyphen.
* Correctly replaces any 'I am' with 'Name is' or 'I'd' with 'Name'd'
There are some issues with identifying verb usage that needs to be changed to end with an 's' but shy of adding the whole English dictionary to the game, I think this'll have to do. It's not *perfect* but it's 99% good.
Check the commits, it breaks it down in the code.
**Changelog**
:cl:
- add: Added the Illism accent to the game. Astro is …
> Illism Accent

- Content.Server/Administration/Commands/SetOutfitCommand.cs
Modified the `SetOutfit` command so any listed `storage:` items also get added to the bags from the `startingGear` prototype.
Mostly for the admemes since it's an admin command, it just ensures that all gear including bag contents are given to the entity that has their outfit set - handy for putting together obscure ghost roles and allows the creation of useful loadouts for admemes.
Checks for bags and items listed in the `storage` part of the `startingGear` prototype and then iterates through the items and inserts them into the equipped bag. See commit for code comments.
n/a
n/a
> SetOutfit command also fills bags from startingGear prototype

- Resources/Prototypes/_Shitmed/Body/Organs/Animal/space.yml
Made several unique transplantable organs contraband due to the abilities they grant.
Transplanting organs that turn someone into a walking weapon should probably not be permitted by Security to occur without good reason!
SOP may need to be updated to reflect this change as well, but I haven't had a look. Security should be able to have contraband organs removed from individuals known to have been transplanted with them, and even examined during a Code Blue or higher, too, in my humble opinion.
* Goliath Hearts, Dragon Lungs and Laser Raptor Eyes are all now Major Contraband on account of the fact they give the transplantee innate weaponry.
* Cobra Glands are Minor Contraband because they grand innate stealth camo while stationary. Not a threatening ability by itself but still not …
> Contraband Update (Organs)

- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/GameRules/pests.yml
- Resources/Prototypes/_ShibaStation/GameRules/events.yml
guh, shiba specific event tweaks and rollup of vent spawns under a single event instead of multiple ones
> More Event Tweaks

- Resources/Prototypes/Entities/Structures/Doors/Airlocks/airlocks.yml
- Resources/Prototypes/lobbyscreens.yml
one day we can burn these in hell, ty
> Ai slop credits

- Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
modsuit breakages strike again smh
> Fix jensen coat

- Content.Server/_ShibaStation/Speech/EntitySystems/IllismAccentSystem.cs
Various fixes with the illeism speech trait; better handling of forename/surname, possessives, subject/object... lots of nerdy language stuff.
It still has some fringe case problems but it's considerably more consistent now.
> Illeism update

- Content.Client/Resist/Systems/EscapeInventorySystem.cs
- Content.Server/Resist/EscapeInventorySystem.cs
- Content.Shared/Resist/Components/CanEscapeInventoryComponent.cs
- Content.Shared/Resist/Systems/EscapeInventorySystem.cs
- Content.Shared/_DV/Carrying/CarryingSystem.cs
Solves some issues that were brought in when CarryingSystem was updated to be predicted; such as not being able to escape anymore and some broken do-afters. Look I have no idea what I'm doing but it works okay.
> Fixes CarryingSystem & EscapeInventory to Shared

- Content.Server/_ShibaStation/Speech/EntitySystems/IllismAccentSystem.cs
Just a few more little things I noticed. This is... getting unnecessarily complex, I'm sorry :<
> More Illeism Fixes

- Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
playerRatio was probably fucking us over due to having low pop. thanks goob <3
> Sloppy antag fix attempt

- Resources/ServerInfo/_ShibaStation/Guidebook/ServerRules/RoleplayRules/ShibaRuleR5-1AcceptableCollateral.xml
Clarifies some stuff brought up previously and also adds new/missing antags for more specific clarification - although some of these should be common sense.
> Rule 5.1 Update

- Content.Server/Chemistry/TileReactions/CleanTileReaction.cs
- Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
- Content.Shared/Fluids/AbsorbentComponent.cs
- Resources/Locale/en-US/fluids/components/absorbent-component.ftl
- Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
- Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
- Resources/Prototypes/_ShibaStation/Entities/Mobs/NPCs/silicon.yml
- Resources/Prototypes/_White/Entities/Effects/puddle.yml
Implements similar footprint AOE cleaning to Floofstation (https://github.com/Fansana/floofstation1/pull/445) however this is a reinterpretation, not a direct port. As a result, footprints are now 'permanent' until cleaned (before they would dissolve after 60 seconds).
Additionally, tile based cleaning such as cleanade foam and space cleaner spray now cleans all 'cleanable' entities on a tile, instead of only the top-most one, meaning a single footprint no longer prevents and entire puddle from being cleaned by these methods.
Finally, OPified the Turbo Cleanbot some more and yoinked it out of the aghost loadout, 'cause ghost roles.
Footprints are a cool feature but having to clean them one by one was a pain, which is why Goob added the self-deletion after a minute. This takes Floof's …
> Big Cleaning Update

- Resources/Prototypes/GameRules/events.yml
> Readded custom voice announcement for category 5 vent spawns

- Resources/ServerInfo/_ShibaStation/Guidebook/ServerRules/CoreRules/ShibaRuleC4BeCivil.xml
No, being rude to people was never allowed, it was always prohibited.
> Fixed a missing linebreak that was breaking formatting, oopsie

- Resources/Prototypes/SoundCollections/lobby.yml
forgot to add the track to the soundcollection lmao
> Add new lobby music track

- Resources/Prototypes/_Shitmed/Entities/Objects/Weapons/Melee/wonderprod.yml
- Resources/Prototypes/_Shitmed/GameRules/events.yml
blah blah basically just the same I did for regular abductor with the alienese accent component and adjusted the event reqs - also added back the cuffs to the wonderprod since they're not borked anymore and Goob STOLE my idea for making abductors sterile (jk it was a very obvious change to make <3)
> Abductor upgrades for Scientist/Agent

- Resources/Prototypes/Maps/Pools/default.yml
Reach is out of the pool. GOODBYE.
> GOODBYE YOU WILL NOT BE MISS (Removed Reach)

- Resources/Prototypes/_ShibaStation/GameRules/events.yml
> Added the snouse to the vent spawns

- Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
- Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
- Resources/Prototypes/_Goobstation/Wizard/wizard.yml
some more adjustments after the first day based on some feedback, a bug report and internal discussion
> Antag reqs tweaks

- Resources/Prototypes/_ShibaStation/Entities/Mobs/NPCs/animals.yml
Remade the snouse prototype as a unique one rather than a child of the mouse mob, since it was causing some issues with the spriting due to inheritance.
No more client console errors!
> Snouse fixes

- Resources/Locale/en-US/reagents/meta/medicine.ftl
Ambuzol+ Is no longer directly made with Zombie Blood, instead it is made with Omnizine, and I changed it to reflect as such
The Description of Ambuzol+
It's mostly cosmetic, simply figured it required updating
Swapped "Blood of the Infected" with "Omnizine" in the Ambuzol+ description
**Changelog**
> Revising Description of Ambuzol+

- Resources/Prototypes/Reagents/toxins.yml
Removed theobromine poisoning from animal stomachs
By Discord vote; admittedly makes animal stomach havers even more OP but ehn.
Commented out the metabolism component from theobromine since it's purely for animal organs only.
> Removed theobromine's poison effect on animal organs (by vote)

- Resources/Prototypes/Reagents/medicine.yml
Made lepo's temp change effects also apply to dead mobs too
Ashing is a serious issue and until shitmed gets husking, this should assist in preventing kinda unfair RRing from a spicy artifact or some idiot igniting a plasma/trit leak. Also lavaland.
Doubled up the temp effect entries in the reagent prototype but added the extra conditional of it working on dead mobs too.
> Leporazine works on dead mobs

- Resources/Prototypes/_ShibaStation/Entities/Objects/Specific/Medical/hypospray.yml
Increased transfer amount for the ethyl medipen to 30u
Can't OD on it and I forgot when I made them to make it do that, so... I'm fixing it.
yaml single line change
> Make ethyl medipens inject their full amount

- Resources/Prototypes/_Shitmed/Entities/Mobs/Player/abductor.yml
- Resources/Prototypes/_Shitmed/GameRules/events.yml
Switched back to our dataset for aliem names
zlorp norp gleeble florp "meme shit" glorple
yaml line changes
> Switch back to our less memey aliem names

- Resources/Prototypes/Catalog/Jukebox/Standard.yml
Simply added new lobby song "ShibaStation" to the jukebox playlist
I wanted to add it here last push, but wanted to make sure it worked.
added song to playlist of jukebox at \Resources\Prototypes\Catalog\Jukebox\Standard.yml
None
**Changelog**
- add: Added "ShibaStation" song to playlist in jukebox
> Add song to jukebox

- Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
Add book to locker.
It's literally called the `BSOManual` but they don't get it? Bruh.
yaml line addition
> Adds BSO CQC manual to the BSO locker

- Resources/Prototypes/_ShibaStation/Roles/Jobs/CentComm/chief_central_commander.yml
Updated the OP admin loadout with even more OP gear
Goob added more funnies and I want to have them all with as few clicks as possible.
yaml update no code
> Make Admeme Loadout Great Again

- Resources/Maps/_ShibaStation/cluster.yml
deroh broke cluster (but it was actually me)
> Fixed Cluster

- Content.Shared/_DV/Salvage/Systems/MiningPointsSystem.cs
Removed the requirement for an ore processor to be linked to the silo to generate points when unprocessed ores are inserted - but kept the requirement that the ore processor MUST be on the station.
It kinda sucks if you just built an Industrial Ore Processor and dumped all your ores in only for it to be worth _nil point_ because you didn't get it linked to the silo first. This ensures that any and all Ore Processors that are on the main Station grid generate points when unprocessed ores are deposited.
The requirement for the processor to be on the Station grid is preserved, though - as I still want salvagers to have to return to the station in order to reap the rewards and prevent them from just leaving the station at round start never to be seen again.
Removed the conditionals that …
> Ore Processor Point Gen Tweaks

- Content.Shared/Standing/StandingStateSystem.cs
Players can no longer flop to get over tables; they must vault.
It's dumb and makes no sense. Vault/climb on tables like a grown up, ya dingbats.
But for real, it basically invalidated vaulting in most cases and wasn't really balanced (or realistic, in my space game). You still get the benefit of avoid gunfire unless you're being clicked directly on - so it still has combat utility, just no longer trespass utility.
Switched the layer toggle from MidImpassibe to BulletImpassible when moving from standing/laying. This ensures bullets still whizz past (unless being directly aimed at) but prevents sliding over tables.
> No Longer Crawl Over Tables

- Resources/Maps/_ShibaStation/atlas.yml
> Added missing mail carrier spawn to Atlas

- Resources/Prototypes/_DV/Entities/Mobs/Species/feroxi.yml
- Resources/Prototypes/_ShibaStation/Entities/Mobs/Species/ariral.yml
Added the footprints component to Feroxi - also modified the Ariral (and added to Feroxi) the use of the reptilian print pattern when barefoot. Fixes #198 
I forgor to add, imdumb.
yaml changes, no code
> Added missing FootPrints component to Feroxi

- Content.Goobstation.Common/Content.Goobstation.Common.csproj
- Content.Goobstation.Common/GlobalUsings.cs
- Content.Shared/Weapons/Ranged/Components/GunComponent.cs
- Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
- Resources/Changelog/GoobChangelog.yml
- Resources/Prototypes/Atmospherics/thresholds.yml
- Resources/Prototypes/Entities/Mobs/Player/jaunt_mobs.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/base_pka.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Rifles/rifle.yml
- Resources/Prototypes/_Goobstation/Heretic/Entities/Mobs/NPC/polymorph.yml
- Resources/Prototypes/_Lavaland/Catalog/Cargo/cargo_cargo.yml
- Resources/Prototypes/_Lavaland/Catalog/Fills/Crates/cargo.yml
- Resources/Prototypes/_Lavaland/Entities/Objects/Devices/flatpack.yml
- Resources/Prototypes/_Lavaland/Entities/Structures/Machines/gateway.yml
- Resources/Prototypes/_Lavaland/tags.yml
goob fixed something real?
Includes the few other PRs that trickled through since then. Testing seems okay? Canary in the coal mine again...
> Post goobmod merge

- Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
BaseVehicle has "save: false" in its prototype, which makes it so whenever the map is serialized, that entity is skipped, I changed that by adding "save: true" to RollingOfficeChairBase entity.
For any maps in Shiba that had updates AFTER the rolling chairs, we still need to go and remap said chairs, they have been skipped.
But now for any new map updates, we won't lose our office chairs anymore.
Rolling chairs are fun, and I like fixing upstream than reverting it! partially solves issue #192 I recommend opening a new issue just to REMAP the chairs that were already lost.
Mythical one line yml change
**Changelog**
> Fixes the mysterious case of Disappearing Office Chairs from maps after they get an update.

- Content.Goobstation.Server/Fishing/FishingSystem.cs
- Content.Goobstation.Shared/Fishing/Systems/SharedFishingSystem.cs
- Resources/Changelog/GoobChangelog.yml
- Resources/Locale/en-US/_Goobstation/servercurrency/server_currency.ftl
- Resources/Prototypes/_Goobstation/GameRules/gamedirector_weights.yml
Quick patch from Goob upstream to fix issues with feeshing.
> Goob patch

- Resources/Prototypes/Entities/Clothing/Multiple/towel.yml
- Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml
- Resources/Prototypes/Loadouts/loadout_groups.yml
Adds the Blueshield's towel to the selection of towels, alongside adding it to the loadout.
The Nanotrasen Representative has one, but the blueshield does not, this fixes this imbalance.
Added a towel under BaseTowel with the colours #005dbf for the general colour, and #212022 for the stripe. The towel is TowelColorBlueshield and it requires 40 hours to be unlocked in the loadout.
Wearing the Blueshield's Towel on the innerwear slot.
The Blueshield's towel in-hand sprite
**Changelog**
:cl:
- add: Added the blueshield's towel!
> Blueshield's Towel
