Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml, Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml, Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml, Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
Removed the antag permission bool from the intern/assistant roles.
Upstream did this and honestly why not; if we want to limit antag availability based on playtime, we should, you know, do that instead of artificially limit it with normal job role requirements.
Removed some bools in prototypes.
=> Let interns be antags

Resources/Locale/en-US/deltav/chat/managers/chat_manager.ftl, Resources/Locale/en-US/deltav/species/species.ftl, Resources/Locale/en-US/species/species.ftl, Resources/ServerInfo/Guidebook/Mobs/DeltaV/Rodentia.xml, Resources/ServerInfo/Guidebook/Mobs/Moth.xml, Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml, Resources/ServerInfo/Guidebook/Mobs/Species.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13CharacterNames.xml, Resources/ServerInfo/_Goobstation/Guidebook/Antagonist/Changelings.xml
Moth people, Slime people and Rodentia are now called Lepidopterans, Amorphians and Rodentians respectively.
Moth and Slime people is just so incredibly uninspired - and 'Rodentia' doesn't sound right referring to a collective of people; yes, it's the valid scientific species name but all other species are named for their collectives, not their genuses (Humans, not Homo Sapiens, etc)
Changed the .ftl and guidebook entries to the new names. The internal names are unchanged because changing them all would be incredibly stupid for so many reasons. It's purely a visual change.
=> Adjustments to Moth, Slime and Rat People Species Names

Resources/Locale/en-US/station-events/events/cargo-gifts.ftl
Changed the .ftl strings for the pizza party gift notification to use a small 'a' and not a capital 'A'.
The old string meant that the message read as 'NanoTrasen has decided to send A small pizza party' which looks duuumb.
Hit the capital A with a koopa shell, causing it to lose it's Super Mushroom power-up and reduce back down to small a.
=> Little 'a' for pizza parties.

Resources/Prototypes/Entities/Structures/Machines/artifact_analyzer.yml
Removed a little bit of fixtures definition in the analyzer prototype to allow for artifacts to be anchored while on top.
It's annoying to have to move them off the platform to do tool usage. Anchored artifacts cannot be scanned, however, so artifacts that are moving around still need to be boxed in, but this can also help with that.
Uuuuh removed one of the fixtures definitions that for some reason was blocking the ability to wrench down artifacts.
=> Allows artifacts to be anchored on top (but cannot be scanned)

Resources/Prototypes/_Goobstation/Entities/Objects/Materials/materials.yml
This is approved on Goob upstream but still not merged and I'm impatient :)
=> Added missing ore tag to bluespace crystals

Content.Server/_EinsteinEngines/Flight/FlightSystem.cs, Content.Shared/Movement/Pulling/Systems/PullingSystem.cs, Content.Shared/Nutrition/EntitySystems/HungerSystem.cs, Content.Shared/_EinsteinEngines/Flight/FlightComponent.cs, Content.Shared/_EinsteinEngines/Flight/SharedFlightSystem.cs, Resources/Changelog/ShibaChangelog.yml, Resources/Locale/en-US/_ShibaStation/flight/flight_system.ftl
Harpy flight now consumes hunger instead of stamina, allowing for longer flights but with potentially worse consequences for resource mismanagement. Additionally they can pull while flying (using their talons, like lizzers with their tails), and take off instantly (this may be changed later).
A species of flying creatures that can only fly for a few seconds before collapsing on the floor is incredibly dumb. Hunger drain is quite high (subject to change) but still permits about a minute of flight for a round-start harpy. For balance, though, being starving (which stops flight and doesn't allow flight) has its own risks due to the movement debuff, but managing hunger means harpy players can better utilise their new ability.
Pulling while flying lets harpies utilise their flight ability …
=> EE Harpy Update Tweaks

Resources/Changelog/ShibaChangelog.yml, Resources/Prototypes/Stacks/Materials/ore.yml, Resources/Prototypes/_Goobstation/Stacks/Materials/materials.yml
Increased ore stack sizes from 30 to 50.
Goob increased (by reverting a WizDen change) ore distribution, meaning more ores to mine. I didn't want to increase the stack too much and invalidate getting the Ore Bag of Holding but a slight bump to ore stacks should hopefully keep average mining sessions about the same length. A reduction in tedium means the station should benefit sooner, hopefully!
Increased the stack count for every ore entry (and bluespace crystals) from 30 to 50.
=> Increase Ore Stacks from 30 to 50

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml, Resources/Prototypes/Voice/speech_emotes.yml, Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/silicon_base.yml, Resources/Prototypes/_EinsteinEngines/Voice/speech_emotes.yml, Resources/Prototypes/_ShibaStation/tags.yml
Added new tags for species specific emotes and whitelisted the speech emotes accordingly, to fix unusable emotes appearing in the emote wheel UI. Also gave IPC boop an icon (reused the beep icon for borgs) and fixed our lizzers not being able to weh on command.
Lizzers need to weh. Also the UI stuff annoyed me.
Bruh look at the diffs?
=> Fixed Emote Jank

Resources/Prototypes/DeltaV/Entities/Mobs/Species/rodentia.yml, Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
Felinids and Rodentian PseudoItem shape adjusted so two can fit in a single duffel and one can fit in a backpack.
Smol Ops are GO
=> hehe funny smols in bags

Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
Jani meta just saw an upset, cleanbot meta is the new meta.
but fr this actually solves a few issues of cleanbots being dumb and getting hung up trying to clean a spot under a door or table and ignoring the rest of the messes until intervened. It's not *perfect* but it's BETTER.
=> Cleanbots can move under doors and tables

Resources/Changelog/Parts/loop-in-rotation.yml, Resources/Prototypes/Maps/loop.yml
Adds Loop Station to low pop; if Packed and Omega can be handled by an average of 5 people, Loop easily can.
=> Loop in rotation

Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
Makes loot bugs be recognised in the `Mouse` faction, making them targets for Shiva, Aves and now Pun Pun. They're a pest that spawns with other non-hostile vent critters, but if ghost role'd they *can* be dangerous, but by nature they seem less interested in attacking crew, so NPC behaviour being 'docile' and ghost behaviour being free agent (and thus potentially hostile) seems fine to me.
=> Lootbugs are vermin

Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
Nerfed lootbugs; sorry not sorry shitters
Lootbugs are incredibly robust for what is non hostile rare critter spawn. They were more tanky than spiders and just a little less tanky than slimes but without the water weakness. This also made them lucrative for ghost role shitter players (you know who you are). We are a no fun allowed fork >:)
Gave lootbugs the same damage thresholds (alive 0, crit 40, dead 60) as mothroaches.
Reduced lootbug bite damage to 2 (piercing)
bug but deader
=> Nerfed lootbug health and damage.

Resources/Prototypes/GameRules/events.yml
Space Cobras are no longer included in the Snake Vent Spawn event.
Shitmed added cobra glands which grant stealth to anyone implanted with them. That's cool and all but now that we've made vent critter spawns a regular event, I don't think the station should have easy access to stealth camo when there's enough players. Salvagers should be bringing back exotic organs instead.
Commented out the Space Cobras from the event mob probability chance bit in the prototype
Imagine space cobras but not.
=> Removed Space Cobras from the vent spawns

Content.Server/Chat/Systems/ChatSystem.Emote.cs
Added an additional check to the emotes system to treat tildes (~) as punctuation, thus allowing emotes to work properly if they end with one.
uwu emotes on you~
Just added an additional check for a ~ along with the standard C# punctuation check.
too lazy, it works as explained.
**Changelog**
:cl:
- fix: Emotes ending in tildes~ now work!
=> Emotes ending in tildes now work properly

Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
Gives chemists access to service and botany under the extended access system.
Chems and botanists usually work hand in hand, but during low pop, sometimes chems might not have a botanist to bounce off. This means chems with botany knowledge can do double duty (should they wish) without needing to be granted access from HoP or other command.
Added Hydroponics and Service to Chemists extended access.
A chemist walks into botany and says; "kudzu grow me some plants and I'll leave you aloe".
**Changelog**
:cl:
- add: Chemists now get access to Botany (and Service) during Extended Access (low pop).
=> Gives chemist access to botany and service under extended access

Resources/Prototypes/GameRules/events.yml
Adjusted derelict borg spawn and ion storm event min pop requirements
Our playerbase currently isn't robust enough to handle malf borgs and AIs; shitter tokens at low pop are cringe.
made number go up
=> Adjusted borg and ion storm min pop requirements for balance

Content.Shared/Access/Systems/AccessReaderSystem.cs
Added an early return if the door access is done by an entity with the 'CentralCommand' access role (Admins and CC).
Log Probe was reporting back when aghosts had interacted with stuff, which can cause confusion if the admin is also in the game in character, but had to aghost to check/interact with something. Creates false positives, even if it does append the access with the (Universal) suffix.
Added a check for the 'CentralCommand' access role on the entity's ID and if so, early returns and doesn't log the access attempt.
=> Prevent aghosts from leaving access logs

Resources/Prototypes/_DV/Body/Organs/harpy.yml
The whole harpy lung gimmick is just annoying when they spend all shift choking on their own CO2. Now they breathe like humans. The footwear debuff is enough balancing for Harpies where they don't also need to be suffocating by merely existing.
=> Robust Harpy Lungs

Content.Shared/GameTicking/Components/GameRuleComponent.cs, Resources/Prototypes/_Goobstation/GameRules/roundstart.yml, Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
flipped a bool from true to false in a desperate attempt to stop readiness requirements from restarting the round. Honestly this should just be 'false' by default, why the fuck would you want the random preset selection to shit itself?
jUsT hAvE a BiGgEr PoP aStRo :|
=> Fix fucking antags (again)

Content.Client/Chat/Managers/ChatManager.cs, Content.Client/Input/ContentContexts.cs, Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs, Content.Client/UserInterface/Systems/Chat/ChatUIController.cs, Content.Client/UserInterface/Systems/Chat/Controls/ChannelSelectorPopup.cs, Content.Server/Chat/Commands/SubtleCommand.cs, Content.Server/Chat/Systems/ChatSystem.cs, Content.Shared/Chat/ChatChannel.cs, Content.Shared/Chat/ChatSelectChannel.cs, Content.Shared/Chat/SharedChatSystem.cs, Content.Shared/Input/ContentKeyFunctions.cs, Resources/Locale/en-US/_Floofstation/chat/managers/chat-manager.ftl, Resources/Locale/en-US/_Floofstation/chat/ui/chat-box.ftl, Resources/Locale/en-US/_Floofstation/escape-menu/ui/options-menu.ftl, Resources/keybinds.yml
Adds 'Subtle Emotes' from Floofstation!
OG PR: https://github.com/Fansana/floofstation1/pull/14
Minor Fix PR: https://github.com/Fansana/floofstation1/pull/63
On top of the ported code, I also added support for Chat Focus by pressing the prefix key similar to other chat prefixes and a keybind option in the settings menu.
Subtle Emotes are effectively the 'whisper' of emotes, meaning that they can only be "seen" by anyone immediately close to you; and cannot be "seen" through walls. Additionally, ghost observers cannot "see" subtle emotes either. Admin Ghosts, naturally, still can, for admin purposes.
The chat prefix to initiate a subtle emote is Minus (-); so for example "-holds your hand" would translate to "Urist McWholesome subtly holds your hand".
Now the player base can hold hands …
=> [Port] Subtle Emotes (From Floofstation)

Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml, Resources/Prototypes/_ShibaStation/Entities/Clothing/Back/modsuit.yml, Resources/Prototypes/_ShibaStation/Entities/Clothing/Head/modsuit.yml
Added the `replaceCurrentClothing` and `blockUnequipWhenAttached` parameters to the `ToggleableClothing` component on the hardsuit and coat clothing bases.
Also fixes the admeme modsuit helmet not having NVG or thermal vision anymore after the MouseVGs fix.
Having to remove a small hair flower to pull up your hood or toggle your hardsuit is DUMB and this is really just a nice QoL change.
Replaced clothing naturally loses its worn benefits, which is the same as removing it, which you would've HAD to have done before. The only real balance change here is that you no longer have to potentially lose your headgear by discarding it on the floor or lose inventory space by stowing it. But I mean... c'mawn...
To account for a "not really bug but confusing symptom", you must have all toggled parts …
=> Toggle Hardsuit Helmets/Coat Hoods over existing headgear

Content.Server/_ShibaStation/Speech/Components/InsideVoiceComponent.cs, Content.Server/_ShibaStation/Speech/EntitySystems/InsideVoiceSystem.cs
Adds the `InsideVoice` component that forces all caps speak into proper case formatted text.
All Capsers need to calm the fuck down and this is an admin applicable component that should ideally never need to be broken out but is there to deal with it.
It only kicks in if more than two words in a sentence are all caps, so you can still emphasise parts of speech. It's also only applied manually by an admin so for the occasional all caps post it also won't apply.
see diffs (why does this section exist?)
Note; the perspective change is because this character has the illeism trait, just ignore that part, look how the big letter become smol.
=> Adds 'Inside Voice' Component

Resources/Maps/Shuttles/mining.yml
Removed the two magic infinite generators with one JRPACMAN on the Mining Shuttle (and a welder fuel tank as a courtesy)
WizDen went hard on salvagers for a reason; and while I don't agree with flat out REMOVING the mining shuttle, I do believe that it needs more 'challenge' to avoid being a free mobile base for the space rangers to avoid interacting with the station for a minimum of two hours.
This change is EASILY overcome by being a good salvager and upgrading the power generation options by so many means, typically SALVAGING. But it at least makes round start salvaging less EZ mode by requiring nursing the generator. The shuttle should have enough power at round start that salvagers can still remote pilot it back to the station first - I'm not a COMPLETE monster.
It's a map edit; just …
=> Mining Shuttle no longer magically powered

Resources/Maps/Shuttles/mining.yml
Replaced the JRPACMAN with a regular PACMAN, anchored it, prefuelled it and also added a second stack of Plasma.
Turns out I'm dumb and JRPACMAN generators are only for LV cable connections. While that still would've worked I didn't want to link two APCs together. The regular PACMAN can charge the shuttle's SMES now.
=> Upgrade JRPACMAN to regular PACMAN on Mining Shuttle

Content.Server/Chat/Systems/ChatSystem.cs, Resources/Locale/en-US/_Floofstation/chat/managers/chat-manager.ftl
Subtle Emotes now display with an asterisk prefix and no longer say 'subtly'.
Both Emotes and Subtle Emotes now ensure the first word after the chat trigger is lower case for grammatical consistency.
Old Subtle Emotes:
`Urist subtly does a thing.`
New Subtle Emotes:
`* Urist does a thing.`
Having to work around the adverb 'subtly' actually limits how you can write your emotes, as an RP nerd.
Lowercasing the first word is also just handy for grammatical consistency and is merely just a petty tweak.
=> Emote/Subtle Emote Tweaks

Content.Server/StationEvents/Components/VentCrittersRuleComponent.cs, Content.Server/StationEvents/Events/VentCrittersRule.cs, Resources/Locale/en-US/deltav/station-events/events/vent-critters.ftl, Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/GameRules/pests.yml
This reverts commit 2fff7eceff9dc6c4cbc540e6549199331b262c7e.
see title dummy
We'd already compensated for the issue of critter spam by reducing the event types down into two grouped events, one for non-hostiles and one for hostiles, where the selection of critters is pooled and varied instead of separate events for each critter type.
This change, while nice to have the callout of the location, effectively broke our spawns by rarely if ever actually spawning anything. This reverts it back to how it was, bringing back mice for non-humans to binge on and varied waves of monsters for the crew to defend against.
=> Revert "[PORT] Vent Critters Rework from Delta-V (#1450)"

Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/_Goobstation/GameRules/roundstart.yml, Resources/Prototypes/_ShibaStation/GameRules/events.yml
Upped Lone Op, Blob and Sleepers by 5 each, and upped Cat3Vent Spawns up too, just a little.
Since minpop calc is based on just 'players on server' and not necessarily 'players in game', ghosts count towards that and now we have more admins, even though we might have 20+ __players__ we may only have 16 people in the actual round, which may make the difference between a steam roll and a crew victory.
Still working on some way to deter ghost parkers who simply want to roll midround antags, though...
=> Increased Min Pop Reqs for Some Events... Again

Content.Client/Atmos/Monitor/UI/AirAlarmWindow.xaml.cs, Content.Server/Atmos/Monitor/Systems/AirAlarmModes.cs, Content.Shared/Atmos/Monitor/Components/SharedAirAlarmComponent.cs, Resources/Locale/en-US/atmos/air-alarm-ui.ftl
Added 'Cycling' and 'Cycling (Wide)' to the Air Alarms; modes that keep air vents distributing air but scrubbers into siphoning mode - effectively creating a complete circulation of all gasses (depending on the number of vents to scrubbers).
With the lowered pressure lockout on vents, this is a real simple way to quickly regulate temperature in areas that may have been affected due to frezon and nitrium leaks. Simply set the system to 'Cycling' and the scrubbers will siphon out the hot/cold gasses and the vents will pump in 20C from the distro.
This isn't a silver bullet but should at least remove some tedium from atmos having to 'pump and dump' manually and in some circumstances it can be more effective than space heaters alone. It also helps account for pressure changes due to …
=> Added 'Cycling' Mode to Air Alarms

Resources/Maps/Shuttles/cargo.yml, Resources/Maps/Shuttles/mining.yml
Tiny adjustment to the shuttles to accommodate the addition of scrubbers venting to space, air alarms and a bonus upgrade to the salvage shuttle to give it space for four forward thrusters (if salvage ever even bother to fix up the shittle in the first place).
lmao bz leak kill everyone :)
it's mapping changes
=> Add air scrubbers to the Cargo and Mining shuttles

Content.Server/Administration/Commands/AGhostCommand.cs, Content.Shared/Ghost/SharedGhostSystem.cs
Adds the `--hidden` or `-h` argument to the `aghost` command to enter an admin ghost/observer on a different visibility layer to be hidden from regular observers/ghosts - while still being visible to other admin ghosts.
Additionally, for the benefit of the admin themselves and other admins, their ghost turns light blue to make it apparent they are in 'extra ghosty' mode. Otherwise they have the same actions, abilities and loadout.
Basically integrated a script that was shared by Crazybrain, so I take no credit for the idea of making extra ghosty aghosts - just making it more convenient for admins to do!
Sometimes admins need to be extra hidden, even from other ghosts. 👀 
Due to some weirdness trying to do this in the prototype direction, instead the aghost command now ensures that the …
=> Adds --hidden argument to aghost command

Resources/Prototypes/Atmospherics/thresholds.yml
Basically just ripped https://github.com/DeltaV-Station/Delta-v/pull/2939 off wholesale :^)
Also included some missing values that DeltaV has that we don't.
The air alarm defaults were also pissing me off but I haven't had enough chance to sit and tinker with the values enough to truly understand what works best. I trust deltanedas's knowledge on this blindly. 
I had already made some adjustments for the additional gasses we have via Goob (BZ, Nitrium and Pluoxium), so hopefully this will make air alarms less cringe overall.
see diffs guh
=> Adjust Air Alarm Threshold Defaults

Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml
Rodentians no longer set off mousetraps.
It's a funny meme, it does kinda make sense and also helps balance their ability to sneak a little, however it also ends up just being more of a general hindrance than a proper balancing thing. For now, this is a stop-gap solution.
In retrospect, I may attempt to add a new component in the future (see, soon™) to only apply the mousetrap triggering if a rodentian is _sneaking_ - at least that way they can still get caught out by hidden traps under tables if they try to go under, instead of climbing over top. For now, though, it's just a straight immunity.
Disabled one line in YAML, lmao
=> Rodentians are mousetrap-proof

Resources/Maps/Shuttles/mining.yml, Resources/migration.yml
Puts the 'Salvage Locator' on the Salvage Shuttle and removes the 'Salvage Magnet' from stations via `migrations.yml`.
It made little sense to keep on the station when we have the shuttle anyway; almost all salvagers would take it off the station (which was always allowed) and install it on the shuttle. This just streamlines that process entirely.
Since the Salvage Magnet and Salvage Locator are different entities, it was easy to yoink the Magnet via migrations and install the Locator to the shuttle - plus it draws less power which is ideal since the changes made to the shuttle earlier mean it requires fuelling.
Added line to `migrations.yml` and mapped the Salvage Locator to the shuttle.
The magnet is actually rotated to face out the blast doors since salvage gets pulled in the direction …
=> Salvage Locator on Salvage Shuttle (Salvage Magnet removed from Stations)

Resources/Locale/en-US/_Lavaland/salvage/lavaland_names.ftl, Resources/Maps/_Lavaland/mining.yml
Renamed the lavaland planet and related shuttle.
`Lavaland Planet` looked god awful next to the station name on the list which usually has some flavour suffixes and prefixes to make them sound all fancy and technical. Since I don't believe it's possible to apply randomised template strings to .ftl files, the lavaland planet will always have the same name, but it'll at least not stick out like a sore thumb.
The `Mining Shuttle` has been renamed to `Lavaland Transport` to alleviate any possible confusion over the reimplemented `Salvage Shuttle`. Besides, you can't pilot the thing that takes you to Lavaland, it only FTLs to fixed positions, so a 'transport' feels more apt.
Ultimately it's all purely petty and aesthetic.
.ftl and prototype changes - single line each, no code.
=> Lavaland name tweaks

Resources/Prototypes/Entities/Structures/Specific/Atmospherics/vox.yml
Fixed vox air alarms breaking the client by adding the missing Pluoxium entries.
game break not gud, now not break so is gud
Added 'Pluoxium' to Vox-related atmos stuff
=> Fix Vox Air Alarms

Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml, Resources/Prototypes/_EinsteinEngines/Entities/Clothing/OuterClothing/hardsuits.yml, Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml, Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/specific.yml, Resources/Prototypes/_Lavaland/Entities/Clothing/explorer_suit.yml
Added (fixed) Cloaks and the new Hardsuits not being able to equip hoods/helmets over existing headgear.
Already did this for other hardsuits/coats, this is just adding the missing stuff.
See diff
=> More Things Equip Over Clothing

Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml, Resources/Prototypes/_Lavaland/Entities/Structures/computers.yml
Replaced the lavaland shuttle and salvage shuttle console screen overlay sprites.
Previous all three (cargo shuttle included) shared the same overlay sprite and telling them apart at a glance was impossible. Now, you can!
Just changed the overlay sprite layer names. Didn't even actually add any new sprites.
=> Unique screen overlays for lavaland shuttle and salvage shuttle consoles

Content.Client/Atmos/Monitor/UI/AirAlarmWindow.xaml.cs, Content.Server/Atmos/Monitor/Systems/AirAlarmModes.cs, Content.Shared/Atmos/Monitor/Components/SharedAirAlarmComponent.cs
'Cycling' modes now make distro air vents work the same was as 'Fill' mode - 4500kPa and bypass pressure locks - in order to be more effective against the scrubbers' siphon mode.
Also moved the Cycling options up in the modes list UI to make them more appealing as an option.
Cycling was pretty effective at 'refreshing' a room of air to help stabilise temperatures but previously air vents only output at normal filtering rates, which often meant that the scrubbers would space the room faster than the distro could replenish the air. This was mitigated by manually setting air vents to 4500kPa outward pressure but was tedious. This automates that and also ensures that the air vents don't totally pressure lock too.
The UI ordering is to help atmos techs discover and understand the use of this …
=> Air Alarm 'Cycling' Mode Improvements

Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/Oni.yml, Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml, Resources/Prototypes/_EinsteinEngines/Entities/Objects/Weapons/Melee/terminus.yml
Added the `AnomalyHost` tag to felinid.yml. Porting some fixes for Oni.yml 
The `AnomalyHost` tag was added to Felinids to enable them to host anomalies. This tag appears to have been absent for so long that it is unclear whether its omission was intentional. Please let me know if any changes are required.
The Oni related changes address a recent commit involving the addition of the Oni tag. When this tag was applied to the Oni prototype, it stopped inheriting tags from its parent. Consequently, it now only has the tag 'Oni' and is missing `CanPilot`, `FootstepSound`, `DoorBumpOpener`, and `AnomalyHost` tags. These changes restore those tags and ensure the introduced weapon in the recent merged pull request works as intended. 
[From this …
=> Felind and Oni Tag Fix 

Resources/Maps/_ShibaStation/amber.yml, Resources/Maps/_ShibaStation/cluster.yml, Resources/Maps/_ShibaStation/omega.yml, Resources/Maps/_ShibaStation/packed.yml, Resources/Prototypes/_ShibaStation/Entities/Markers/Spawners/vehicles.yml
Added office chair spawn markers for mapping and mapped some to maps that had lost their office chairs.
Vehicles don't get saved when maps are saved, and now that office chairs are vehicles, they'll start disappearing when maps are edited and saved after the fact. 
We lost chairs on four maps after I modified them with some fixes, so I made the office chair spawners and mapped them so they'll spawn on those maps again.
You can't rotate spawners, though - so all office chair spawn facing south, which is lame, but your average person won't care.
yaml and mapping
=> Rolly chair spawners and mapping

Resources/Prototypes/Guidebook/species.yml, Resources/Prototypes/Reagents/toxins.yml, Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml, Resources/Prototypes/_Goobstation/Entities/Mobs/Species/tajaran.yml, Resources/ServerInfo/Guidebook/Mobs/Felinid.xml, Resources/ServerInfo/Guidebook/Mobs/Species.xml, Resources/ServerInfo/Guidebook/Mobs/Tajaran.xml, Resources/ServerInfo/Guidebook/Mobs/_DV/Rodentia.xml
Re-added both the Felinid species icon to the species page of the guidebook, as well as its corresponding guidebook entry.
Adjusted Rodentia to match Felinids in being easier to knock down, while making Tajara more resistant to knockdowns in accordance with their increased size on ShibaStation. 
Additionally, since Tajara are not small, they now inherit the base density and size components that most species use. This adjustment ensures they no longer have tiny hitboxes or an unrealistically low density.
Updated the guidebook entries for Felinid, Rodentia, and Tajara to better reflect their current state. While they could still use further refinement for consistency, I’ve done my best. Many other species entries remain incomplete, but these are among the more polished ones in my opinion. …
=> Adjustments to Felinid, Rodentia, Tajara, and their guidebooks, plus animal poison changes.

Resources/Prototypes/Entities/Mobs/Species/reptilian.yml, Resources/Prototypes/_DV/Entities/Mobs/Species/harpy.yml, Resources/Prototypes/_DV/Entities/Mobs/Species/vulpkanin.yml, Resources/ServerInfo/Guidebook/Mobs/Species.xml
- Added the `AnomalyHost` tag to `harpy.yml`, `reptilian.yml`, and `vulpkanin.yml`
- Fixed a typo in the `Species.xml` guidebook entry.
The `AnomalyHost` tag was added to Harpies, Vulpkanins, and Reptilians to ensure they host anomalies like everyone else. 
A small typo fix in `Species.xml`, because.
**Changelog**
:cl:
- fix: Harpies, Reptilians, and Vulpkanins join the can host anomalies club.  
- fix: Minor typo correction in the Species guidebook entry.
=> Tag Fixes & Typo Correction

Resources/Prototypes/Entities/Structures/Doors/Shutter/blast_door.yml, Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml
I've removed the `NoRot` property from `ShutterFrame` and `BlastDoorFrame`. Without this property, the `Type: Transform` component is unnecessary, as it is inherited from the parent `BaseStructureDynamic`, so I’ve removed that as well.  
Additionally, I have assigned both of them the `type: Rotatable`, which allows them to be rotated. This applies only during the construction stage; once completed, none of these changes will be in effect.  
The `NoRot` property ensured that the Frames could **_not_** be rotated and defaulted to an `Angle.Zero` rotation. With this change, both shutters and blast door frames will retain the rotation of their construction ghosts as well. 
It was suggested on Discord that we should be able to place shutters that do not only face south, and I agree. I also …
=> Allow Shutter and Blast Door Frames to Be Rotated During Construction

Resources/Prototypes/Entities/Objects/Tools/spray_painter.yml
Added more options to the spraypainter for pipes colors based on canister's colors
When painting pipes i always ran out of colors, this way there are more options and they are also exactly same color code as the canisters.
Edited \Resources\Prototypes\Entities\Objects\Tools\spray_painter.yml to contain more color codes / options
None
**Changelog**
- add: Added more colors to the spraypaint tool based on canisters colors
- remove: Removed "Blue" since the color code is basically same as distro
- tweak: Changed the color of "Frezon" to be a bit lighter due to in low light situations the color would look too much like distro
=> Spraypainter more atmos colors

Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_Goobstation/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/cargo.yml, Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/medical.yml, Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/service.yml
Added Manipulators, Matter bins, Capacitors and LV cables to techfabs with printable machine circuit boards
To allow departments to assemble there machine boards without having to find a separate lathe.
Added lathe recipe packs to cargo, medical and service techfabs.
Updated the goob and wizden pack lists for each techfab.
**Changelog**
:cl:
- add: Added parts for machine construction to some techfabs.
=> Add basic parts to some techfabs

Resources/Prototypes/Body/Organs/Animal/animal.yml
Added the trash tag to animal organs and made mouse stomachs edible
It's a pain in the arse to have to manually pick up each organ to put it in the recycler and also mice stomachs were inedible for some reason?
Just made the mouse stomachs be the same as rat stomachs, and added the trash tag to animal organ prototypes. All yaml.
=> Animal organs are trash (and mouse stomachs are edible)

Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/GameRules/midround.yml, Resources/Prototypes/GameRules/random_sentience.yml, Resources/Prototypes/GameRules/roundstart.yml, Resources/Prototypes/_Goobstation/GameRules/roundstart.yml, Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml, Resources/Prototypes/_Shitmed/GameRules/events.yml
Lowered player count requirements and player ratios to get more antags to roll while working within our recognised average and peak player counts. Also a few adjustments to max reoccurrences and other small tweaks.
Now that we have playtime reqs for antags, I'm less concerned about antag tourism and antag rollers - and likewise we just don't get _as many_ antags as we _could_ due to higher requirements. We've been operating for several months now and seem to have found our average and peak player counts, so antag spawn and gamerule requirements have been adjusted to meet these numbers. There should be less 'sleepy shifts' where it's purely PvE going forward.
number change in yaml lmao
=> Various antag/event tweaks to make them more common

Content.Server/Anomaly/AnomalySystem.Generator.cs, Content.Server/StationEvents/Events/GasLeakRule.cs
Shortened the admin announcements for Anomaly Spawn events and Gas leak events to include only immediately relevant details, while adding extra information to the actual admin logs. 
While the coordinates are usually sufficient to figure out where the gas leak or anomaly has spawned, we still need a map ID to fully support teleporting anywhere. I can't think of a situation where it would be absolutely necessary, but just in case, it's now included in the event logs.
Using the tp command, we can easily pull the coordinates from the admin announcement message and do `tp x y` to jump to the event location. And as mentioned, if it happens to be on a different map, the map ID is included in the admin logs as well. In that case, we can use `tp x y mapID`. That, and these coordinates match up …
=> Improved Anomaly/Gas Leak Announcements; Expanded Admin Logs

Content.Server/_Lavaland/Salvage/ShelterCapsuleSystem.cs
fixes #175
Disabled the use of preloaded shelter grids in `ShelterCapsuleSystem.cs` due to a seemingly flawed implementation specific to this system. The fallback method is now always used.
While preloading grids seems to work in other contexts, check the `LoadMapRule` for their implementation. Within `ShelterCapsuleSystem` it is currently not working as intended. Grids spawned from capsules seem to skip normal map initialization, which leads to issues like missing `ContainerFillComponent` not able to fill door containers with `DoorElectronics`. 
These issues are not related to the Shelters themselves. if you replace the shelter grids usually spawned to, say, a shuttle, those shuttle doors will also have the same door issues. 
This fallback solution may be slightly less performant since …
=> Lavaland Bluespace Shelter Fix 

Resources/Prototypes/Entities/Mobs/Species/base.yml, Resources/Prototypes/Entities/Mobs/Species/skeleton.yml, Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml, Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/silicon_base.yml, Resources/Prototypes/_Goobstation/Entities/Mobs/Species/yowie.yml
Commented out the carrying component from all species.
Kind of but not really fixes #177 - a real fix would be to address the problems that carrying has now, but ultimately I don't see much need to keep carrying in its current form. It's less effective than just pulling a downed body out of danger, the grabbing system has throwing now which is something carrying permitted exclusively, and the bugs that can occur due to certain situations are literally game breaking. It's only purpose it had was either for RP or for shitters to be annoying with - and unfortunately I don't see much value in it.
The system itself hasn't been _removed_ from the codebase, and it may be looked at later to be fixed up and re-enabled for all species, but for now it's a low priority.
Commented out lines in yaml …
=> Disabled carrying on all species

Content.Client/_DV/Abilities/CrawlUnderObjectsSystem.cs, Content.Server/_DV/Abilities/CrawlUnderObjectsSystem.cs, Content.Shared/_DV/Abilities/CrawlUnderObjectsComponent.cs, Content.Shared/_DV/Abilities/SharedCrawlUnderObjectsSystem.cs, Resources/Prototypes/Entities/Mobs/Species/base.yml, Resources/Prototypes/Entities/Mobs/Species/skeleton.yml, Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml, Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
Permit all species to be able to crawl/sneak under tables/furniture while crawling/prone/downed/whatever like Rodentians. Rodentians, however, can still sneak while standing, and move a little bit faster than previously while sneaking.
Changes to laying preventing moving over tables and giving Rodentians the ability to vent crawl natively permit sneaking/crawling under to be something that all species can benefit from now, with the caveat that they must be lying down.
A new parameter has been added to the CrawlUnderObjects system which permits sneaking while standing, which was the previous default behaviour but is now unique to Rodentians. By default it's false, meaning that other species must be laying down to toggle the ability. The action will appear while laying down, and disappear …
=> All Species can Crawl/Sneak Under Tables while Prone

Resources/Prototypes/Loadouts/Miscellaneous/survival.yml, Resources/Prototypes/_ShibaStation/Entities/Mobs/Species/ariral.yml, Resources/Prototypes/_ShibaStation/Reagents/biological.yml
Fixes #193 #195 and possibly #196
Adjusts ariral reagents to be more potent, but makes the melee injector administer less per hit.
Arirals need survival boxes!
They bled a bit TOO much too easily; arith treatment was basically a death sentence without gauze. While I like this as a medical challenge, it was still a bit TOO excessive. Their clotting rate has been upped as well as their blood regen amounts however it's still lower than average, so they'll most likely still need gauze or other bleed-stopper options. Finally a use for inap?
Hopefully stops the interact message popping up on the target now too; since the funny meme is that they can't get hugged.
yaml adjustments, no code
=> Ariral tweaks & fixes

Content.Shared/Doors/Components/DoorComponent.cs, Content.Shared/Doors/Systems/SharedDoorSystem.cs, Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
This reverts commit f4c4c12934c519e717595938416ac57ed39837ba.
The idea is nice in concept but it's scuffed in practice, with it causing odd behaviour with doors that shouldn't be influenced by this new feature. The problems it brings outweighs the minor convenience it provides, and we've decided we don't want it anymore.
PR revert; PR was very tightly made (good job Ilya) so there's no issues reverting this.
Goob's modular overhaul that's still pending probably reintroduces this feature, judging by the PRs on their repo, so when that finally gets rolled out, I'll have to remember to go and remove/disable the functionality again. As for now, though, no breaking changes.
=> Revert "proximity airlock opening (#2076)"

Content.Goobstation.Shared/Changeling/Components/ChangelingIdentityComponent.cs, Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/_Goobstation/Changeling/Objectives/changeling.yml, Resources/Prototypes/_Goobstation/GameRules/midround.yml, Resources/Prototypes/_Goobstation/Heretic/Objectives/heretic.yml, Resources/Prototypes/_Goobstation/Wizard/gamerules_wizard.yml, Resources/Prototypes/_Shitmed/GameRules/events.yml
Adjusted the requirements and frequency of the midround antag events.
We need to pump the brakes a little on the chaos _just enough_ to keep room for MRP. Every round now has the chance to have at least four antagonists at a modest (by our standards) population. Heretics, Changelings and the Wizard have now been capped to one instance per round - Wizard army should be kept to an admeme :kek:
Changeling biomass drain has been reduced by 25% to let them go longer before they _need_ to absorb DNA to survive, since our rounds go a bit longer. A modest changeling that doesn't want to murderbone can probably go on about two feeds a standard shift round, with the need to do another per extension - which seems pretty fair, the crew shouldn't be letting The Thing wander around unopposed!
Mostly …
=> Midround Antag Rebalancing

Resources/Prototypes/Entities/Objects/Misc/kudzu.yml
Reduce tendon health down from 40 to 12
Fixes #225
While I appreciate that the result of a meat anom should be a challenge, they felt FAR too difficult to manage even with multiple crew; turns out they have 4x the health of regular kudzu on top of the fact that they HEAL when they grow (unlike kudzu). Rather than totally nerf the challenge, they've had their health dropped from 40 to 12, which is still a smidge more than regular plant kudzu but should still be one-shotable with a decent weapon. Before, due to the massive health pool, rapid growth and healing on growth, it was practically impossible to deal with without first spacing the room and going in hazmat style. While that conceptually sounds "fun", in practice it was more annoying than its worth.
yamlmaxxing
**Changelog**
:cl:
- …
=> Reduce tendon health down from 40 to 12

.github/workflows/changelog.yml
GitHub related stuff; downstreams may want to be aware of this if they have self-hosted runners for GitHub actions configured. I don't think we have any major downstreams at the moment, though!
=> Switch to GH runner instead of self-hosted

Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml, Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml, Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml, Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml, Resources/Prototypes/Roles/Jobs/Science/research_director.yml, Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml, Resources/Prototypes/Roles/Jobs/Security/warden.yml
Added `Captain` to the Command (+ Warden) `extendedAccess` job component parameters.
People are allergic to playing Captain but want to tide in to get his gear when they have to be Acting Captain instead; at least this way they can just walk in and give themselves AA instead of having to break in like common criminals.
Command are still expected to follow SOP correctly; meaning that only the present Command member who sits at the top of the Chain of Command should be rummaging through Captain's sock drawer.
yamlmao
**Changelog**
:cl:
- add: Command (and Warden) get access to the Captain's Room during 'Extended Access' population counts. Command should still be following SOP and the CoC correctly, but now you can stop breaking into the Captain's room every shift.
=> Give Command access to Cappy's Room under Extended Access conditions

Content.Server/Chat/Systems/ChatSystem.cs, Content.Server/_Shitcode/Wizard/Systems/GhostVisibilitySystem.cs
The `Summon Ghosts` spell no longer allows living, non-admin players from hearing Dead Chat.
There's been some confusion over the validity of seeing Dead Chat as a living player mid-round, as Dead Chat is considered Out of Character. Rather than impose a dynamic rule on ghost players that they must become IC if the spell is used, as per vote on Discord we instead simply hide Dead Chat from players who are **not**:
* Ghosts
* Admins
The spell still makes the ghost sprites visible and from an admin's perspective we're still okay with players gleaning information as a result of this, as per the Wizard 'causing chaos' - although this may be subject to change (and isn't in the scope of this PR anyway).
Added a `bool` to the `GhostVisibilitySystem` that always returns false and instead filters …
=> No Dead Chat from Summon Ghosts Spell
